### ISSUE TITLE
Can't Login with WWW only without

### ISSUE THREAD

**Issue by mgarf** [wpo365/wpo365-login#15]
When trying to login into the wordpress site and using www in the URL. it redirects to microsoft and then back to the wordpress standard login screen with a "Login may have been tampered with" message. However without WWW i am able to login fine.

**Comment by wpo365** [comment]
Hi ... Am I right when I assume that you can login when you don't use WWW? You will see the error "Login may have been tampered with" when a cookie that stores a validation token cannot be found. So my guess is that a cookie has been set for http://example.com but the return address configured is http://www.example.com. I suspect that the plugin therefore cannot find the cookie. It's difficult to advice on the best configuration, from where I stand. But in general it is actually better to choose one main URL instead of offering both the long (with www) and the short (without www) variants.
For the plugin it's really important that the base url is equal to the redirect URL in the WPO365 settings and that both are equal to the redirect URL configured in Azure AD. And depending on your Wordpress / URL rewrite config it may be a good idea to add a trailing slash e.g. http://example.com/ to both the WPO365 setting and the Azure AD redirect URL.

**Comment by mgarf** [comment]
gotcha, thank you. Ill fiddle based on what you suggested. I appreciate the quick response!

**Comment by wpo365** [comment]
Thanks for you support and feedback to help improve the plugin. I will now close this issue, as it was resolved.
