### ISSUE TITLE
Could not find expected key in keys retrieved from Microsoft

### ISSUE THREAD

**Issue by G2Ocean** [wpo365/wpo365-login#17]
Hi - we are experiencing a redirect loop after logging in to our intranet via wpo365 plugin (version 3.0). We have added the required trailing slash as described her https://www.wpo365.com/troubleshooting-the-wpo365-login-plugin/ so this should not be the problem.

Examining the log files after enabling debugging mode, I find the "Could not find expected key in keys retrieved from Microsoft" error message there. I'm able to dump out both the KID and the keys header, so both of these exist. The code is set to pull codes from https://login.microsoftonline.com/common/discovery/keys

Any idea what the problem could be?

**Comment by wpo365** [comment]
Hi @G2Ocean , it's a bit difficult to guess what the reason could be. It sounds, as if you would be able to dump the keys you receive as well as your KID and send them over to me. If so, then I'd like to have a look ... The code was changed for version 2.9 as it turned out that the structure of the file had changed. However, right now I cannot reproduce any such behavior at my end. Another issue may be with some encoding in the keys file. If you can post the your data here or send them to me by email (info at wpo365.com) then I'm sure we'll quickly find out what is going on.

**Comment by G2Ocean** [comment]
Thanks. Keys + kid submitted by email.
