### ISSUE TITLE
Errors/redirect to wp-login (sometimes)

### ISSUE THREAD

**Issue by techinaflash** [wpo365/wpo365-login#18]
These are the errors that I get when traveling to the root of my site.  Sometimes I don't get these errors and it goes through no issue.  

Warning: Cannot modify header information - headers already sent by (output started at /home/flashadmin/public_html/kb/wp-login.php:75) in /home/flashadmin/public_html/kb/wp-content/plugins/wpo365-login/Wpo/Util/Helpers.php on line 22

Warning: Cannot modify header information - headers already sent by (output started at /home/flashadmin/public_html/kb/wp-login.php:75) in /home/flashadmin/public_html/kb/wp-content/plugins/wpo365-login/Wpo/Util/Helpers.php on line 23

Warning: Cannot modify header information - headers already sent by (output started at /home/flashadmin/public_html/kb/wp-login.php:75) in /home/flashadmin/public_html/kb/wp-content/plugins/wpo365-login/Wpo/Util/Helpers.php on line 24
Your login might be tampered with. Please contact your System Administrator.

**Comment by techinaflash** [comment]
Anyone out there in support land?

**Comment by wpo365** [comment]
Hi @techinaflash ... Yes, somebody's here and I'm really sorry to take so long to respond. I must have slipped my attention.

There are a few things happening here:
1. The error "Cannot modify header information" seems to indicate that when the login plugin is verifying whether the user is authenticated, Wordpress has already started sending a response. This may be caused by another plugin or theme (out of the box this would not happen) that basically starts sending a response earlier as it should.
2. The error "your login may be tampered with" is an error that occurs when a validation code that the plugin attached to the request to Microsoft to authenticate the user has expired, is not found or is simply wrong.

I suspect that there is an interference with another plugin that causes our plugin to work OK. I will investigate whether I can ensure for the plugin to execute as first.

Thanks for your patience.

**Comment by wpo365** [comment]
@techinaflash In version 3.5 the plugin starts sooner than before with validating the session. This should prevent the first type of error "Cannot modify header information".

However, the error  "your login may be tampered with" most likely occurs, because the URL used when you return from Microsoft's login screen to your Wordpress site is ever so slightly different. The most likely differences are:

**- http vs. https**
This may happen when you have different redirect-URLs in the app registration in Azure AD and in the WPO365 settings.

**- www.yoursite.com vs. yoursite.com**
This may happen when you first navigate to https://yoursite.com but when you return you land at https://**www**.yoursite.com (either by .htaccess or URL rewrite or because you have configured the redirect-URL to be different from the URL you use to access you app.

Ps, it seems that the safari browser is more critical / handles the redirect ever so slightly different from any other browser and therefore the latter error is more likely to occur.
