### ISSUE TITLE
Same Authentication for both application

### ISSUE THREAD

**Issue by kshivks** [wpo365/wpo365-login#26]
Currently I have one mobile app, it's using Azure AD for authenticating users . Now I have developed one WordPress site and it's using Azure AD(Wordpress+office 365 login) for authenticating users. Now I have to integrate my WordPress site to my mobile app. My question is while clicking this WordPress app page in mobile app it's should not ask for login again to authenticate. Instead of it, it has to authenticate using same Azure AD authentication which mobile application is using. Is it possible ? if yes, how to do ? any example code

**Comment by wpo365** [comment]
@kshivks Sorry to say, but this scenario is currently not supported. Not because the plugin does not support it, but because you use two separate Azure AD protected resources. However, if your mobile app is also browser based and the user has successfully authenticated and you'd then redirect him / her to WordPress then the user will be redirected to Azure AD only to discover that the user is already signed in and then the user is redirected by to the requested WordPress page ...
