### ISSUE TITLE
JWT Exception

### ISSUE THREAD

**Issue by kmnathancse** [wpo365/wpo365-login#29]
Team,

This plugin was working fine for few days and all of sudden it is giving the PHP error that

 Fatal error: Class ‘Firebase\JWT\ExpiredException’ not found in E:\xampp\htdocs\wp-content\plugins\wpo365-login\Firebase\JWT\JWT.php on line 142

I tried to update plugin to latest version and did not help. i did not setup leeway value. if i set that up it is giving an error that login is tampered. can you anyone help me on the same?

Thanks,
Meenakshinathan

**Comment by wpo365** [comment]
The error that the class not found is a bug and will be fixed with the next update. However, this won't solve your problem. The login information that the plugin receives from Microsoft contains a timestamp until when the information is considered valid and this timestamp is compared with the server's time. Now, if your server is returning the wrong time e.g. because the server time is suddenly wrong, you will see this error. By the way, it's recommended to set up a leeway time of about 300 (= 5 minutes). Try and increase that value (it's in seconds) to see if things improve e.g. try setting it to 3600 (= 1 hour) and see if things start working again. However, please check your server's clock first.
