### ISSUE TITLE
Security Groups Redirect

### ISSUE THREAD

**Issue by bryanwillis** [wpo365/wpo365-login#32]
I got the security group feature working, but ran into an issue with users who weren't in the security group of users allowed to access the website. If the user isn't allowed to access the site they will be redirected to the wp-login.php page as long as that page is in the blacklist.

https://example.com/wp-login.php?reauth=1&login_errors=NOT_IN_GROUP

<img width="1680" alt="screen shot 2018-10-04 at 5 26 10 pm" src="https://user-images.githubusercontent.com/4042621/46512931-eb2bf980-c81b-11e8-891b-dcd3a5c8036e.png">

This also occurs if a user not in a security group that is whitelisted is already logged into office and navigates to the site.

Alternatively, if _wp-login.php_ is not in the blacklist and is blocked then an error will occur because of too many redirects (this may be different depending on server settings. 

<img width="1557" alt="screen shot 2018-10-04 at 9 36 01 pm" src="https://user-images.githubusercontent.com/4042621/46513315-94bfba80-c81d-11e8-8861-49f1c306b4d6.png">

I'm not sure if I have a setting that could be changed to change this behavior but I tried several of them like:

"Intercept manual logins"
"Goto after"
"Post sign-out URL"

The default behavior seems like it should be that if a user in not in the "Groups whitelist" when they try to log in then they they get logged out back to the login page. It seems that this is what microsoft is trying to do, but for some reason it's causing a loop of some sort. 

I'm guessing this issue might not occur if the entire site and homepage weren't locked down (like the homepage wasn't blocked), but I could be wrong.

Assuming this isn't something I just messed up on, maybe the best solution (but probably means more work for you), is to add another option to the settings like "Failed Security Group Login URL". This scenario would help improve user experience by allowing site admins/owners to send these unauthenticated domain users to a custom blacklisted page or external page where they can post information on why they can't access the site like

"You currently do not have access to these company resources. Please contact your site administrator for details on how to gain access."

As always, thanks for the great plugin and let me know if you want me to do/check anything.

**Comment by wpo365** [comment]
Hi @bryanwillis ... All of what you wrote in your issue is basically "by design". When you activate the Groups Whitelist (simply entering Azure AD Group IDs and making sure the Azure AD application registration returns the group ID's upon login) the plugin will check whether the user that attempts to sign into your website is a member of any of the groups listed in the Groups Whitelist. If this isn't the case, the plugin will prevent that user from signing into your (WordPress) website and therefore will redirect you to the one page for which no login is required: The WordPress login page. And as you already noted, the user is sent there with an error code (visible in the URL _login_errors=NOT_IN_GROUP_) and an additional message is shown on the login page because of that (Access Denied. Please contact your System Administrator). 

Removing the wp-login-php page from the blacklist - especially in this scenario - would however cause an indefinite loop indeed because the user, who is not allowed to signin, will be redirected to page that then again automatically tries and sign in that user: A loop you cannot escape from anymore! Also, I would highly recommend excluding the wp-login.php (or any other login form in case you have renamed it to reduce Brute Force attacks) so that you as an administrator can still sign into your WordPress website if for any reason the Microsoft authentication and thus the WPO365 plugin will fail. You then still would require a way to sign into your website ...

So all in all I guess you're not really experiencing any issue because the plugin does what it should do: Preventing users to sign into your WordPress website when they are not a member of selected Azure AD groups. However, I assume that you'd like to enhance the user experience in case this happens. This is what you suggest with the solution to have a separate blacklisted page that is not the wp-login.php page that shows the user a more friendly error message. I will put this on the roadmap and it should be possible publishing an update within the next two weeks.

Ps, thanks and feel free contacting me directly by email if you have any further questions!

**Comment by wpo365** [comment]
No replies received so I'm closing this issue.
