### ISSUE TITLE
Doesn't work, can't login anymore

### ISSUE THREAD

**Issue by andrerav** [wpo365/wpo365-login#9]
Hi,

After configuring both Azure AD and this plugin I must have somehow misconfigured something. Now the login page on wordpress says that the O365 plugin is not yet configured, and I can't login with my regular user anymore either (it just fails silently and returns me to the login page).

I have moved the plugin away from the plugins directory to mitigate the situation.

How do I change the configuration for the plugin while its offline?

I have done several O365 integrations before, and it is not clear to me what could be wrong. Can you give me a few pointers towards common problems with configuring this plugin?

Thanks,
Andreas

**Comment by wpo365** [comment]
Hi @andrerav ... I wasn't able to collect much feedback so far, so I am happy with every feedback and more than willing to support you until it's working. 

**Log on with a Wordpress Only account**
First things first: If you're not able to log on using a Wordpress-only account then I suspect that you have a customized login page and that this page isn't called "wp-login.php". When you go to the "WPO365 Options" and select the first section "Azure AD" then towards the bottom there is a setting called "Pages Blacklist". Any page name where the plugin should not try and authenticate the user should be listed here. 

**Not configured yet**
You may get the the error "Wordpress + Office 365 login not configured yet. Please contact your System Administrator." only when you try to navigate to the front end and one of the following settings in the "WPO365 Options" is empty: Tenant ID, Application ID or Redirect URI. If these are, however, filled out by you, then please read on with next section.

**Debug Mode**
There is also another section called "Miscellaneous". Here you can click to enable "Debug Mode". This will write quite a lot of debug information in the Wordpress debug log (or you default PHP log, depending on hosting partner). You may want to send me your log at info@wpo365.com (or reply here with the relevant lines). I can then probably quickly see where it goes wrong.

Ps, Please also let me know what version of Wordpress and PHP you're using.

**Comment by wpo365** [comment]
@andrerav I can confirm that I can reproduce the behavior of not being able to login with Wordpress-Only account when WPO365-login options are missing. I will post an update a.s.a.p.

**Comment by andrerav** [comment]
Thanks, when I am able to login in again I will be able to provide you with more details about my WPO365 settings.

**Comment by wpo365** [comment]
@andrerav One more thing: The fact that Wordpress won't let you log on as normal Wordpress user anymore can be worked around when you navigate to /wp-login.php and make sure that the query string parameter redirect_to is not present. This causes the behavior you experienced. I will, however, look how this can be programmatically be avoided,, because it's pretty ugly :)

**Comment by wpo365** [comment]
@andrerav I've pushed version 1.6 to Wordpress this time it should be possible to log on as Wordpress-only user when WPO365 is not yet correctly configured.

**Comment by andrerav** [comment]
Thanks, everything seems to be working now. However, I seem to have misunderstood the purpose of this plugin -- I only want the O365 authentication to kick in for wp-admin, not the entire site :) Is this possible to do?

**Comment by wpo365** [comment]
Thanks @andrerav ... Right now it works exactly the other way around: Authenticating O365 users for Wordpress front-end and creating corresponding WP users if not already created. I can take this into consideration but may arrive a days / weeks from now. Ps, I'll close the issue for now and a rating over at the [Plugin Directory](https://wordpress.org/plugins/wpo365-login/) is of course highly appreciated :)

**Comment by andrerav** [comment]
Alright, would be really nifty if WPO365 only kicked in if a user tried to login :) I can add that as a separate issue with a more detailed description.

**Comment by wpo365** [comment]
@andrerav If you want, you can have a look whether the latest update meets your requirements. I have updated the readme.txt and you can now choose between an 'intranet' and an 'internet' scenario (see the admin-dashboard --> WPO365 Options --> User Management tab).

Here you'll find an updated description [readme.txt](https://wordpress.org/plugins/wpo365-login/)

**Comment by andrerav** [comment]
Hi and thanks! For existing users, this works great! However, users that don't have a matching Wordpress account will [see this message](https://i.imgur.com/2Hs1eCq.png) when trying to log in.

**Comment by wpo365** [comment]
Would it be possible to post (or send me by mail at info@wpo365.com, you have to check whether or not it contains any confidential information) the Wordpress debug log? Because this could mean that the decryption of the information received from MSFT was not successful for some reason. 

The idea is basically that the plugin will create a Wordpress user for every Azure Active Directory user. When The user information is retrieved from Azure Active Directory (in the form of an id token) the WP user is searched for by its email address or if not found a user is created (and next time the matching WP user is found). However, the error you now ran into is happening way before this, namely when this incoming token is being processed. Or (less likely) because a "secret" value that I sent along with the initial request has been changed (hence: Your login might be tampered with).

**Comment by wpo365** [comment]
@andrerav I strongly suspect that you test the plugin on a (local host) test environment and that your PHP configuration is not correctly set up to access your Certifcate Authority (CA). The plugin requires this access because it wants to verify the SSL host its contacting when getting the information from Azure Active Directory. To configure your environment properly, you can proceed as follows:

- Download [this file](https://github.com/wpo365/wpo365-login/files/1351060/cacert.pem.txt) and rename it to cacert.pem and save it at some location in your PHP directory
- Update your php.ini file and look for the section [curl] and uncomment and update the following key: curl.cainfo = "C:/wamp/bin/php/php5.5.0/cacert.pem"
- Look for the section [openssl] and uncomment and update the following key: openssl.cafile= "C:/wamp/bin/php/php5.5.0/cacert.pem"
- If you run (like me) WAMP on your local host you need to update also phpForApache.ini
- Restart the web server

Ps, On most hosted environments this problem will not occur as this configuration is addressed by the hosting provider.

**Comment by wpo365** [comment]
@andrerav I have released an updated version of our plugin that won't validate the SSL host and peer (but it can be activated with a new setting). Let me know if this may have solved your problem and if I can be of any further assistance.

**Comment by andrerav** [comment]
Everything seems to work perfectly now after updating to 1.13. Thanks!
